name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 992652/backendart:$(date +%s)
    - name: run docker image
      run: docker run -p 4100:4100 992652/backendart
    - name: push to dockerhub
      run: docker push 992652/backendart
