name: Push-to-EC2

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest


    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
      defaults:
        run:
          working-directory: /home/ubuntu

    - name: Deploy to my EC2 instance
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "./"
        REMOTE_HOST: "13.212.189.24"
        REMOTE_USER: "ubuntu"
        TARGET: "/home/ubuntu/html-docs-hello-world/"
    - run: pwd
    - run: ls
    - run: sudo chmod 777 script.sh
    - run: sudo sh script.sh -t
    - run: sudo sh script.sh -p
