name: Push-to-EC2

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest


    steps:
    - name: Checkout the code
      uses: actions/checkout@v1

    - name: Deploy to my EC2 instance
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "./"
        REMOTE_HOST: "18.138.249.41"
        REMOTE_USER: "ubuntu"
        TARGET: "/home/ubuntu/"
    - run: pwd
    - run: ls
    - run: ls -l script.sh
    - run: sudo chmod +x script.sh
    - run: ls -l script.sh
    - name: Test
      run: |
          sudo cat <<EOF > ./script.sh
          #!/bin/sh
          exit 1
          EOF
          sudo chmod +x ./script.sh
          
          
          #!/bin/bash
          sh ./script.sh -p
          if [ $? -ne 0 ]; then
              echo PASS
          fi;
          EOF
          echo END
