name: Push-to-EC2

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu@18.138.249.41


    steps:
    - name: Checkout the code
      uses: actions/checkout@v1

    - name: Deploy to my EC2 instance
      uses: appleboy/ssh-action@master
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
    - run: pwd
    - run: ls
    #- run: ls -l script.sh
    - run: sudo chmod +x docker.sh
    - run: ls -l docker.sh
    - run: sh docker.sh
